---
title: "Costa Rica stations map"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyr)
library(dplyr)
library(magrittr)

library(ggplot2)

library(leaflet)
library(leaflet.extras)
```

```{r data loading, include=FALSE}
coord_clean <- read.table("dat/coord_clean.txt", header = TRUE)

exploitable_fit_integral <- read.table("dat/exploitable_fit_integral.csv", header = TRUE, sep = ",")
```

```{r}
coord_clean %<>% mutate(label = paste(sep="", "<b>Station n°", id, " :</b><br><ul><li>lat = ", y.wgs, "<li>lon = ", x.wgs, "</ul>"))

exploitable_fit_integral %<>% mutate(label = paste(sep="", "<b>Station n°", id, "</b><br><ul><li>lat = ", y.wgs, "<li> lon = ", x.wgs,"</ul>Parameters (duration ", dur, " minutes) :<ul>", "<li>μ = ", μ,"<li>ϕ = ", ϕ, "<li>ξ = ", ξ, "</ul>"))
```

# Map of stations

```{r map}
factpal <- colorFactor(topo.colors(20), coord_clean$basin)

leaflet(coord_clean) %>%
  addTiles() %>%
  addCircleMarkers(lng = ~x.wgs,
              lat = ~y.wgs,
             popup = ~label,
             label = ~as.character(id),
             stroke = FALSE,
             color = ~factpal(basin),
             fillOpacity = 0.8) %>%
  addResetMapButton()
```




# Map of Location parameter


```{r gevfit.location}
xipal <- colorNumeric("Oranges", exploitable_fit_integral$μ)


leaflet(exploitable_fit_integral) %>%
  addTiles() %>%
  addCircleMarkers(data = exploitable_fit_integral %>% filter(dur == 360),
                    lng = ~x.wgs,
                    lat = ~y.wgs,
                   popup = ~label,
                   label = ~as.character(id),
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = ~xipal(μ),
                    group = "360") %>%
  addCircleMarkers(data = exploitable_fit_integral %>% filter(dur == 720),
                    lng = ~x.wgs,
                    lat = ~y.wgs,
                   popup = ~label,
                   label = ~as.character(id),
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = ~xipal(μ),
                    group = "720") %>%
  addCircleMarkers(data = exploitable_fit_integral %>% filter(dur == 1440),
                    lng = ~x.wgs,
                    lat = ~y.wgs,
                   popup = ~label,
                   label = ~as.character(id),
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = ~xipal(μ),
                    group = "1440") %>%
  addLayersControl(baseGroups = c("360", "720", "1440")) %>%
  addLegend(pal = xipal, values = ~μ, opacity = 1) %>%
  addResetMapButton()
```

# Map of Scale parameter

```{r gevfit.scale}
xipal <- colorNumeric("Oranges", exploitable_fit_integral$ϕ)

leaflet(exploitable_fit_integral) %>%
  addTiles() %>%
  addCircleMarkers(data = exploitable_fit_integral %>% filter(dur == 360),
                    lng = ~x.wgs,
                    lat = ~y.wgs,
                   popup = ~label,
                   label = ~as.character(id),
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = ~xipal(ϕ),
                    group = "360") %>%
  addCircleMarkers(data = exploitable_fit_integral %>% filter(dur == 720),
                    lng = ~x.wgs,
                    lat = ~y.wgs,
                   popup = ~label,
                   label = ~as.character(id),
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = ~xipal(ϕ),
                    group = "720") %>%
  addCircleMarkers(data = exploitable_fit_integral %>% filter(dur == 1440),
                    lng = ~x.wgs,
                    lat = ~y.wgs,
                   popup = ~label,
                   label = ~as.character(id),
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = ~xipal(ϕ),
                    group = "1440") %>%
  addLayersControl(baseGroups = c("360", "720", "1440")) %>%
  addLegend(pal = xipal, values = ~ϕ, opacity = 1) %>%
  addResetMapButton()
```


# Map of Shape parameter

```{r gevfit.shape}
xipal <- colorNumeric("Oranges", exploitable_fit_integral$ξ)

leaflet(exploitable_fit_integral) %>%
  addTiles() %>%
  addCircleMarkers(data = exploitable_fit_integral %>% filter(dur == 360),
                    lng = ~x.wgs,
                    lat = ~y.wgs,
                   popup = ~label,
                   label = ~as.character(id),
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = ~xipal(ξ),
                    group = "360") %>%
  addCircleMarkers(data = exploitable_fit_integral %>% filter(dur == 720),
                    lng = ~x.wgs,
                    lat = ~y.wgs,
                   popup = ~label,
                   label = ~as.character(id),
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = ~xipal(ξ),
                    group = "720") %>%
  addCircleMarkers(data = exploitable_fit_integral %>% filter(dur == 1440),
                    lng = ~x.wgs,
                    lat = ~y.wgs,
                   popup = ~label,
                   label = ~as.character(id),
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = ~xipal(ξ),
                    group = "1440") %>%
  addLayersControl(baseGroups = c("360", "720", "1440")) %>%
  addLegend(pal = xipal, values = ~ξ, opacity = 1) %>%
  addResetMapButton()
```


